window.addEventListener('load',()=>{try{installCareerOSV32()}catch(e){console.error('Career OS V3.2 failed',e)}},{once:true});

function installCareerOSV32(){
  S.resources=S.resources||{snapshot:{cash:0,investments:0,debt:0,monthlyIncome:0,monthlyExpense:0,passiveIncome:0},goals:[],months:[],hideAmounts:false,updatedAt:''};
  S.promptMeta=S.promptMeta||{favorites:[],recent:[],usage:{}};
  S.pendingConfidence=Array.isArray(S.pendingConfidence)?S.pendingConfidence:[];
  S.manualEntries=Array.isArray(S.manualEntries)?S.manualEntries:[];
  const oldNormalize=normalizeState;normalizeState=function(s){const o=oldNormalize(s);o.resources=o.resources||{snapshot:{cash:0,investments:0,debt:0,monthlyIncome:0,monthlyExpense:0,passiveIncome:0},goals:[],months:[],hideAmounts:false,updatedAt:''};o.promptMeta=o.promptMeta||{favorites:[],recent:[],usage:{}};o.pendingConfidence=arr(o.pendingConfidence);return o};
  const oldDefault=defaultState;defaultState=function(){const o=oldDefault();return{...o,resources:{snapshot:{cash:0,investments:0,debt:0,monthlyIncome:0,monthlyExpense:0,passiveIncome:0},goals:[],months:[],hideAmounts:false,updatedAt:''},promptMeta:{favorites:[],recent:[],usage:{}},pendingConfidence:[]}};
  injectV32Sections();injectV32Styles();

  const oldApply=applyDailyPatchV3;
  applyDailyPatchV3=function(patch){
    const before=Object.fromEntries((S.careerModel||[]).map(x=>[x.diagnosisId,x.diagnosisConfidence]));
    oldApply(patch);
    arr(patch.careerModelUpdates).forEach(u=>{
      const model=S.careerModel.find(x=>x.diagnosisId===u.diagnosisId);if(!model)return;
      const old=before[u.diagnosisId];if(old!==undefined)model.diagnosisConfidence=old;
      else model.diagnosisConfidence=Number(u.currentConfidenceReference||0);
      const range=arr(u.proposedConfidenceRange);
      S.pendingConfidence=S.pendingConfidence.filter(x=>!(x.diagnosisId===u.diagnosisId&&x.patchId===patch.patchId));
      S.pendingConfidence.push({diagnosisId:u.diagnosisId,patchId:patch.patchId,date:patch.date,range:range.length===2?range:[model.diagnosisConfidence,Number(u.newConfidence??model.diagnosisConfidence)],reason:u.confidenceUpdateReason||u.reason||'',requiresWeeklyConfirmation:true});
    })
  };

  const oldRenderToday=renderToday;renderToday=function(){oldRenderToday();renderDecisionCockpit()};
  const oldRenderCareer=renderCareer;renderCareer=function(){oldRenderCareer();renderResources()};
  const oldRenderGrowth=renderGrowth;renderGrowth=function(){oldRenderGrowth();renderPendingConfidence();renderAbilitiesAsHistory()};
  const oldRenderTools=renderTools;renderTools=function(tab='prompts'){oldRenderTools(tab);if(tab==='prompts')enhancePromptLibrary()};
  const oldRenderManual=renderManualEntries;renderManualEntries=function(){oldRenderManual();enhanceManualCards()};
  const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();renderDecisionCockpit();renderResources();renderPendingConfidence();renderAbilitiesAsHistory();enhanceManualCards()};
  document.title='Jett · Career OS V3.2';const side=document.querySelector('.side-title');if(side)side.textContent='CAREER OS · V3.2';renderAll();
}

function injectV32Sections(){
  const status=document.getElementById('todayStatusRow');if(status&&!document.getElementById('decisionCockpit'))status.insertAdjacentHTML('beforebegin','<section id="decisionCockpit" class="decision-cockpit"></section>');
  const career=document.getElementById('career');if(career&&!document.getElementById('resources-v32')){
    const finance=document.getElementById('life-finance');finance?.insertAdjacentHTML('beforebegin','<section class="content-section" id="resources-v32"><div class="section-title split-title"><div><div class="eyebrow">PERSONAL RESOURCES</div><h2>个人财务</h2><p>管理资源和目标，不做逐笔记账，也不把财务变成职业附属品。</p></div><button class="secondary" id="toggleMoneyPrivacy">隐藏金额</button></div><div id="resourceDashboard"></div></section>');
    document.querySelector('[data-scroll="life-finance"]')?.setAttribute('data-scroll','resources-v32');const b=document.querySelector('[data-scroll="resources-v32"]');if(b)b.textContent='个人财务';
  }
  const cm=document.getElementById('career-model');if(cm&&!document.getElementById('pending-confidence'))cm.insertAdjacentHTML('afterend','<section class="content-section" id="pending-confidence"><div class="section-title"><div class="eyebrow">WEEKLY CONFIRMATION QUEUE</div><h2>本周待Review信号</h2><p>Daily只提交建议区间；正式Confidence由周复盘确认。</p></div><div class="stack" id="pendingConfidenceFeed"></div></section>');
}

function renderDecisionCockpit(){
  const box=document.getElementById('decisionCockpit');if(!box)return;const w=currentWeek();const undone=w.tasks.filter(t=>!S.checks[t.id]);const log=S.dailyLogs.find(x=>x.date===S.selectedDate);const risk=S.pendingConfidence?.length?`${S.pendingConfidence.length}项诊断变化等待周复盘确认`:!log?'今天尚未形成工作记录':'当前没有高优先级风险';const next=undone[0]?.title||'完成当天工作记录并确认明日安排';
  box.innerHTML=`<article><small>今天最重要的一件事</small><h3>${esc(next)}</h3><p>${undone[0]?esc(undone[0].reason||'推进当前课程主干'):'保持记录与行动闭环'}</p></article><article><small>当前最大的风险</small><h3>${esc(risk)}</h3><p>${S.pendingConfidence?.length?'不要在单日证据下直接修改长期判断。':'基于当前网站数据生成，不做无依据推断。'}</p></article><article><small>下一步</small><h3>${log?'继续执行并补充事实':'完成今日口述与V3 Patch导入'}</h3><p>先做最小有效动作，再进入详细页面。</p></article>`
}

function renderResources(){
  const box=document.getElementById('resourceDashboard');if(!box)return;const r=S.resources,s=r.snapshot||{},net=num(s.cash)+num(s.investments)-num(s.debt),surplus=num(s.monthlyIncome)+num(s.passiveIncome)-num(s.monthlyExpense),savingRate=num(s.monthlyIncome)>0?Math.max(0,surplus/num(s.monthlyIncome)*100):0,emergency=num(s.monthlyExpense)>0?num(s.cash)/num(s.monthlyExpense):0;const money=v=>r.hideAmounts?'••••••':formatMoney(v);
  box.innerHTML=`<div class="metrics resource-metrics">${[['净资产',money(net)],['月度结余',money(surplus)],['储蓄率',savingRate.toFixed(1)+'%'],['应急资金',emergency.toFixed(1)+'个月'],['被动收入',money(s.passiveIncome)]].map(x=>`<article class="metric"><small>${x[0]}</small><b>${x[1]}</b></article>`).join('')}</div><div class="grid2"><article class="card"><div class="eyebrow">FINANCIAL SNAPSHOT</div><h3>当前财务快照</h3><div class="finance-form"><label>现金<input data-fin="cash" type="number" value="${num(s.cash)}"></label><label>投资资产<input data-fin="investments" type="number" value="${num(s.investments)}"></label><label>负债<input data-fin="debt" type="number" value="${num(s.debt)}"></label><label>月收入<input data-fin="monthlyIncome" type="number" value="${num(s.monthlyIncome)}"></label><label>月支出<input data-fin="monthlyExpense" type="number" value="${num(s.monthlyExpense)}"></label><label>月被动收入<input data-fin="passiveIncome" type="number" value="${num(s.passiveIncome)}"></label></div><button class="primary small-btn" id="saveFinanceSnapshot">保存快照</button></article><article class="card"><div class="eyebrow">GOALS</div><h3>财务目标</h3><div id="financeGoals">${arr(r.goals).length?r.goals.map(renderGoal).join(''):'<p class="muted">还没有目标。MBA可以作为其中一个目标，但不拥有特殊页面。</p>'}</div><div class="goal-add"><input id="goalName" placeholder="目标名称"><input id="goalTarget" type="number" placeholder="目标金额"><input id="goalCurrent" type="number" placeholder="当前金额"><input id="goalDate" type="date"><button class="secondary small-btn" id="addFinanceGoal">添加目标</button></div></article></div>`;
  box.querySelector('#saveFinanceSnapshot')?.addEventListener('click',()=>{box.querySelectorAll('[data-fin]').forEach(i=>s[i.dataset.fin]=num(i.value));r.updatedAt=localISO();save();renderResources();toast('财务快照已保存')});
  box.querySelector('#addFinanceGoal')?.addEventListener('click',()=>{const name=$('#goalName').value.trim();if(!name)return toast('请输入目标名称');r.goals.push({id:uid('goal'),name,target:num($('#goalTarget').value),current:num($('#goalCurrent').value),date:$('#goalDate').value});save();renderResources();toast('目标已添加')});
  box.querySelectorAll('[data-goal-delete]').forEach(b=>b.onclick=()=>{r.goals=r.goals.filter(x=>x.id!==b.dataset.goalDelete);save();renderResources()});
  const privacy=document.getElementById('toggleMoneyPrivacy');if(privacy&&!privacy.dataset.bound){privacy.onclick=()=>{r.hideAmounts=!r.hideAmounts;privacy.textContent=r.hideAmounts?'显示金额':'隐藏金额';save();renderResources()};privacy.dataset.bound='1'}if(privacy)privacy.textContent=r.hideAmounts?'显示金额':'隐藏金额';
}
function renderGoal(g){const pct=num(g.target)>0?Math.min(100,num(g.current)/num(g.target)*100):0;return `<article class="goal-row"><div><b>${esc(g.name)}</b><small>${g.date?`目标 ${esc(g.date)}`:'未设置日期'}</small></div><div class="goal-progress"><i style="width:${pct}%"></i></div><span>${pct.toFixed(0)}%</span><button class="ghost-btn" data-goal-delete="${g.id}">×</button></article>`}

function renderPendingConfidence(){const box=document.getElementById('pendingConfidenceFeed');if(!box)return;box.innerHTML=arr(S.pendingConfidence).length?S.pendingConfidence.map(x=>{const d=S.diagnoses.find(y=>y.id===x.diagnosisId);return `<article class="entry"><header><span>${esc(x.date||'')}</span><span class="tag learn">待周复盘确认</span></header><h3>${esc(d?.topic||x.diagnosisId)}</h3><p><b>建议区间：</b>${arr(x.range).join('% — ')}%</p><p>${esc(x.reason||'新增Daily Evidence，尚未正式修改Confidence。')}</p></article>`}).join(''):'<div class="empty">当前没有待确认的Confidence变化。</div>'}
function renderAbilitiesAsHistory(){const section=document.getElementById('ability-map');if(!section)return;section.querySelector('h2').textContent='历史能力基础档案';section.querySelector('p').textContent='保留旧版能力信息作为背景参考，不再由AI独立升级。';section.querySelector('[data-quick="ability"]')?.remove();if(!section.matches('details')){section.classList.add('ability-history');}}

function enhanceManualCards(){document.querySelectorAll('.manual-card').forEach(card=>{const id=card.querySelector('[data-manual-used]')?.dataset.manualUsed;if(!id||card.querySelector('.manual-extra-actions'))return;const item=S.manualEntries.find(x=>x.entryId===id);const wrap=document.createElement('div');wrap.className='manual-extra-actions';wrap.innerHTML=`<button class="secondary small-btn" data-manual-fav>${item?.favorite?'★ 已收藏':'☆ 收藏'}</button><select data-manual-validity><option value="valid" ${item?.validity==='valid'?'selected':''}>仍有效</option><option value="partial" ${item?.validity==='partial'?'selected':''}>部分有效</option><option value="invalid" ${item?.validity==='invalid'?'selected':''}>已失效</option><option value="review" ${!item?.validity||item?.validity==='review'?'selected':''}>待确认</option></select>`;card.querySelector('.manual-footer')?.prepend(wrap);wrap.querySelector('[data-manual-fav]').onclick=()=>{item.favorite=!item.favorite;save();renderManualEntries()};wrap.querySelector('[data-manual-validity]').onchange=e=>{item.validity=e.target.value;item.history=arr(item.history);item.history.push({date:localISO(),note:`有效性更新为${e.target.options[e.target.selectedIndex].text}`});save();renderManualEntries()}})}

function enhancePromptLibrary(){const content=document.getElementById('toolContent');if(!content||content.querySelector('.prompt-v32-toolbar'))return;const grid=content.querySelector('.prompt-grid');if(!grid)return;const toolbar=document.createElement('div');toolbar.className='prompt-v32-toolbar';toolbar.innerHTML='<button data-prompt-view="favorite" class="active">★ 收藏</button><button data-prompt-view="recent">最近使用</button><button data-prompt-view="all">全部Prompt</button><input id="promptSearchV32" placeholder="搜索Prompt">';grid.before(toolbar);const cards=[...grid.children];cards.forEach(card=>{const copy=card.querySelector('[data-copy]');if(!copy)return;const key=copy.dataset.copy;card.dataset.promptKey=key;const fav=document.createElement('button');fav.className='prompt-fav';fav.textContent=S.promptMeta.favorites.includes(key)?'★':'☆';fav.onclick=()=>{S.promptMeta.favorites=S.promptMeta.favorites.includes(key)?S.promptMeta.favorites.filter(x=>x!==key):[...S.promptMeta.favorites,key];save();renderTools('prompts')};card.prepend(fav);copy.addEventListener('click',()=>trackPromptUse(key))});let view='favorite';const apply=()=>{const q=(document.getElementById('promptSearchV32')?.value||'').toLowerCase();cards.forEach(c=>{const key=c.dataset.promptKey;const match=!q||c.innerText.toLowerCase().includes(q);const visible=view==='all'||view==='favorite'&&S.promptMeta.favorites.includes(key)||view==='recent'&&S.promptMeta.recent.includes(key);c.style.display=match&&visible?'':'none'})};toolbar.querySelectorAll('[data-prompt-view]').forEach(b=>b.onclick=()=>{view=b.dataset.promptView;toolbar.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));apply()});toolbar.querySelector('input').oninput=apply;if(!S.promptMeta.favorites.length)view='all';apply()}
function trackPromptUse(key){S.promptMeta.usage[key]=num(S.promptMeta.usage[key])+1;S.promptMeta.recent=[key,...S.promptMeta.recent.filter(x=>x!==key)].slice(0,8);save()}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}function formatMoney(v){return new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:0}).format(num(v))}
function injectV32Styles(){if(document.getElementById('v32-style'))return;const s=document.createElement('style');s.id='v32-style';s.textContent=`.decision-cockpit{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.decision-cockpit article{border:1px solid #2b5360;background:linear-gradient(145deg,#0b1e29,#07151e);border-radius:12px;padding:16px}.decision-cockpit small{color:var(--cyan);letter-spacing:.08em}.decision-cockpit h3{margin:8px 0}.decision-cockpit p{color:var(--muted);font-size:11px}.resource-metrics{grid-template-columns:repeat(5,1fr)}.finance-form{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0}.goal-add{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.goal-row{display:grid;grid-template-columns:1fr 1.2fr 42px 24px;gap:8px;align-items:center;padding:10px 0;border-bottom:1px solid var(--line2)}.goal-row small{display:block;color:var(--muted)}.goal-progress{height:6px;background:#17303c;border-radius:8px;overflow:hidden}.goal-progress i{display:block;height:100%;background:var(--cyan)}.ghost-btn{background:none;border:0;color:var(--muted);font-size:18px;cursor:pointer}.manual-extra-actions{display:flex;gap:6px;align-items:center}.prompt-v32-toolbar{display:flex;gap:8px;align-items:center;margin-bottom:12px;grid-column:1/-1}.prompt-v32-toolbar button{background:#0d2430;color:var(--muted);border:1px solid var(--line);border-radius:7px;padding:8px 10px}.prompt-v32-toolbar button.active{color:var(--cyan);border-color:var(--cyan)}.prompt-v32-toolbar input{margin-left:auto;max-width:240px}.prompt-card{position:relative}.prompt-fav{position:absolute;right:10px;top:10px;background:none;border:0;color:var(--amber);font-size:18px;cursor:pointer}.ability-history{opacity:.78}@media(max-width:900px){.decision-cockpit{grid-template-columns:1fr}.resource-metrics{grid-template-columns:1fr 1fr}.finance-form,.goal-add{grid-template-columns:1fr}.prompt-v32-toolbar{flex-wrap:wrap}.prompt-v32-toolbar input{margin-left:0;max-width:none;width:100%}}`;document.head.appendChild(s)}
