window.addEventListener('load',()=>{try{installV42Demo()}catch(e){console.error('V4.2 demo failed',e)}},{once:true});
function installV42Demo(){
 injectDemoButtonV42();injectDemoShellV42();injectDemoStylesV42();document.title='Jett · Career OS V4.2';const side=document.querySelector('.side-title');if(side)side.textContent='CAREER OS · V4.2'
}
const DEMO_STEPS_V42=[
 {view:'today',selector:null,kicker:'WELCOME',title:'5分钟看懂 Career OS',text:'这不是一个会自行分析的AI网站。你在ChatGPT里完成口述、诊断和复盘，网站负责保存、展示、搜索和执行已确认的Patch。',you:'跟随Demo浏览真实页面，不会修改任何数据。',ai:'负责理解你的工作、形成诊断和输出Patch。',site:'负责保存事实、Evidence、Review和长期档案。'},
 {view:'today',selector:'#decisionCockpit',kicker:'STEP 1 · TODAY',title:'每天先看驾驶舱',text:'首页只回答今天最重要的事情、当前风险和下一步。这里的内容来自网站中已经存在的课程、记录和待Review状态，不是假装由网站AI生成。',you:'打开网站，先确认今天该做什么。',ai:'无需参与这一小步。',site:'根据已保存数据做确定性汇总。'},
 {view:'today',selector:'[data-quick="daily"]',kicker:'STEP 2 · DAILY INPUT',title:'向ChatGPT口述今天做了什么',text:'点击“记录今天”复制或查看Daily Prompt，然后回到你和ChatGPT的对话中自然口述工作、问题、处理过程和反馈。',you:'自然描述，最后明确说“口述结束”。',ai:'生成Daily Work Record、Daily Diagnosis和V3/V4兼容Patch。',site:'只接收你粘贴导入的结构化Patch。'},
 {view:'today',selector:'#dailyRecordDetail',kicker:'STEP 3 · WORK RECORD',title:'回看某一天完整做了什么',text:'导入后，这里会保存任务目标、处理过程、结果、未解决事项、独立程度、反馈和下一步。半年后仍能清楚理解当时发生了什么。',you:'需要时按日期回看。',ai:'已在导入前完成整理和脱敏。',site:'展示可阅读工作记录，不重新解释。'},
 {view:'growth',selector:'#career-model',kicker:'STEP 4 · CAREER MODEL',title:'查看长期判断，而不是看星级评分',text:'Career Model展示当前可修正的诊断假设、Evidence Strength和正式Confidence。Daily只能新增证据，正式Confidence必须由Weekly Review确认。',you:'关注哪些判断仍在观察、哪些需要周度确认。',ai:'审查支持、反对和替代解释。',site:'展示正式状态与历史，不自行提高分数。'},
 {view:'growth',selector:'#diagnosis-lifecycle',kicker:'STEP 5 · DIAGNOSIS',title:'管理诊断的生命周期',text:'Diagnosis可以处于已提出、收集证据、获得支持、受到挑战、已接受、已推翻或已关闭。它不是永久标签，也不会无限堆积。',you:'按状态筛选，查看当前进行中的假设。',ai:'在周度复盘中决定是否改变生命周期。',site:'保存每次正式变化和Confidence历史。'},
 {view:'growth',selector:'#evidence-timeline',kicker:'STEP 6 · EVIDENCE',title:'搜索判断背后的证据',text:'Evidence Explorer支持按关键词、Diagnosis、方向和来源筛选。你可以快速查到某个长期判断究竟基于哪些真实工作、口试、练习或反馈。',you:'搜索主题，例如低功耗、ATE或Debug。',ai:'在Patch里说明每条Evidence支持或反对什么。',site:'提供检索、过滤和关联跳转。'},
 {view:'growth',selector:'#problem-journal',kicker:'STEP 7 · WORK MANUAL',title:'把小诀窍积累成问题手册',text:'Linux快捷键、脚本修改、仿真环境复用等小问题不必进入深度职业诊断。使用问题手册Prompt，把困境和有效操作整理成下次能迅速找到的条目。',you:'描述当时的困境和最终有效方法。',ai:'整理成清楚、可检索、可复用的手册JSON。',site:'保存关键词、有效性、收藏和复用记录。'},
 {view:'growth',selector:'#review-layer-v4',kicker:'STEP 8 · REVIEW',title:'每周和每月把材料交给ChatGPT复盘',text:'网站先导出本周或本月材料，你把文件交给ChatGPT。分析完成后，将Weekly或Monthly Patch导回网站，正式更新Career Model并保存复盘档案。',you:'导出材料并发送给ChatGPT。',ai:'完成周/月Review，确认Confidence、课程和下一步。',site:'执行已确认的Patch并展示档案。'},
 {view:'resume',selector:'.portfolio-hero',kicker:'STEP 9 · PORTFOLIO',title:'把长期记录沉淀成履历资产',text:'履历页是Engineering Portfolio，不只是PDF副本。工作记录、项目和Review中有价值的内容可以由ChatGPT整理成简历Bullet、项目故事和技能更新。',you:'在阶段节点要求ChatGPT提取职业资产。',ai:'基于已知事实生成可使用表达，并标记证据不足项。',site:'保存Portfolio、版本和候选内容。'},
 {view:'career',selector:'#resources-v32',kicker:'STEP 10 · RESOURCES',title:'用财务与目标支持长期选择',text:'长期规划中的个人财务只做资源管理：现金、资产、负债、现金流、应急资金和多个目标。MBA只是普通目标之一，不主导整个页面。',you:'按月更新汇总数字和目标进度。',ai:'需要时帮助做月度复盘和情景分析。',site:'计算确定性指标并保存趋势。'},
 {view:'today',selector:'.top-actions',kicker:'FINISH',title:'你的日常使用只需要三种节奏',text:'每天：口述并导入Daily Patch。遇到小诀窍：记录问题手册。每周或每月：导出材料给ChatGPT复盘，再导入Review Patch。其他模块主要用于回看和决策。',you:'保持输入轻量，定期备份网站数据。',ai:'承担复杂分析、结构化和更新建议。',site:'成为长期可信的个人数据库。'}
];
let demoIndexV42=0,demoActiveV42=false,demoPreviousViewV42='today';
function injectDemoButtonV42(){const actions=document.querySelector('.top-actions');if(!actions||document.getElementById('openUsageDemo'))return;const b=document.createElement('button');b.id='openUsageDemo';b.className='secondary small-btn demo-launch-v42';b.textContent='使用Demo';b.onclick=startDemoV42;actions.insertBefore(b,actions.firstChild)}
function injectDemoShellV42(){if(document.getElementById('usageDemoV42'))return;document.body.insertAdjacentHTML('beforeend','<div class="demo-overlay-v42" id="usageDemoV42" aria-hidden="true"><div class="demo-backdrop-v42"></div><aside class="demo-panel-v42"><div class="demo-progress-v42"><span id="demoProgressTextV42">1 / 12</span><i id="demoProgressBarV42"></i></div><button class="demo-close-v42" id="closeDemoV42" aria-label="退出Demo">×</button><div class="eyebrow" id="demoKickerV42"></div><h2 id="demoTitleV42"></h2><p class="demo-main-v42" id="demoTextV42"></p><div class="demo-roles-v42"><article><b>你</b><p id="demoYouV42"></p></article><article><b>ChatGPT</b><p id="demoAiV42"></p></article><article><b>网站</b><p id="demoSiteV42"></p></article></div><div class="demo-actions-v42"><button class="secondary" id="demoPrevV42">上一步</button><button class="primary" id="demoNextV42">下一步</button></div><small class="demo-safe-v42">Demo只浏览和高亮页面，不写入、不覆盖任何数据。</small></aside></div>');
 document.getElementById('closeDemoV42').onclick=stopDemoV42;document.querySelector('#usageDemoV42 .demo-backdrop-v42').onclick=stopDemoV42;document.getElementById('demoPrevV42').onclick=()=>showDemoStepV42(demoIndexV42-1);document.getElementById('demoNextV42').onclick=()=>{if(demoIndexV42>=DEMO_STEPS_V42.length-1)stopDemoV42();else showDemoStepV42(demoIndexV42+1)};document.addEventListener('keydown',e=>{if(!demoActiveV42)return;if(e.key==='Escape')stopDemoV42();if(e.key==='ArrowRight')document.getElementById('demoNextV42').click();if(e.key==='ArrowLeft')document.getElementById('demoPrevV42').click()})}
function startDemoV42(){demoActiveV42=true;demoIndexV42=0;demoPreviousViewV42=document.querySelector('.nav button.active')?.dataset.view||'today';document.getElementById('usageDemoV42').classList.add('open');document.getElementById('usageDemoV42').setAttribute('aria-hidden','false');document.body.classList.add('demo-running-v42');showDemoStepV42(0)}
function stopDemoV42(){demoActiveV42=false;clearDemoHighlightV42();document.getElementById('usageDemoV42')?.classList.remove('open');document.getElementById('usageDemoV42')?.setAttribute('aria-hidden','true');document.body.classList.remove('demo-running-v42');switchDemoViewV42(demoPreviousViewV42);window.scrollTo({top:0,behavior:'smooth'})}
function showDemoStepV42(index){demoIndexV42=Math.max(0,Math.min(DEMO_STEPS_V42.length-1,index));const step=DEMO_STEPS_V42[demoIndexV42];switchDemoViewV42(step.view);clearDemoHighlightV42();setTimeout(()=>{let target=step.selector?document.querySelector(step.selector):null;if(target){target.classList.add('demo-target-v42');target.scrollIntoView({behavior:'smooth',block:'center'})}else window.scrollTo({top:0,behavior:'smooth'});document.getElementById('demoKickerV42').textContent=step.kicker;document.getElementById('demoTitleV42').textContent=step.title;document.getElementById('demoTextV42').textContent=step.text;document.getElementById('demoYouV42').textContent=step.you;document.getElementById('demoAiV42').textContent=step.ai;document.getElementById('demoSiteV42').textContent=step.site;document.getElementById('demoProgressTextV42').textContent=`${demoIndexV42+1} / ${DEMO_STEPS_V42.length}`;document.getElementById('demoProgressBarV42').style.width=`${(demoIndexV42+1)/DEMO_STEPS_V42.length*100}%`;document.getElementById('demoPrevV42').disabled=demoIndexV42===0;document.getElementById('demoNextV42').textContent=demoIndexV42===DEMO_STEPS_V42.length-1?'完成Demo':'下一步'},80)}
function switchDemoViewV42(view){const nav=document.querySelector(`.nav button[data-view="${view}"]`);if(nav&&!nav.classList.contains('active'))nav.click()}
function clearDemoHighlightV42(){document.querySelectorAll('.demo-target-v42').forEach(x=>x.classList.remove('demo-target-v42'))}
function injectDemoStylesV42(){if(document.getElementById('v42-demo-style'))return;const s=document.createElement('style');s.id='v42-demo-style';s.textContent=`.demo-launch-v42{border-color:#4d7180}.demo-overlay-v42{position:fixed;inset:0;z-index:9999;display:none}.demo-overlay-v42.open{display:block}.demo-backdrop-v42{position:absolute;inset:0;background:rgba(1,7,12,.64);backdrop-filter:blur(2px)}.demo-panel-v42{position:absolute;right:24px;top:24px;bottom:24px;width:min(430px,calc(100vw - 32px));background:#07141e;border:1px solid #31596a;border-radius:16px;box-shadow:0 24px 80px rgba(0,0,0,.55);padding:26px;overflow:auto}.demo-close-v42{position:absolute;right:17px;top:15px;border:0;background:transparent;color:#9bb0bc;font-size:28px;cursor:pointer}.demo-progress-v42{display:flex;align-items:center;gap:12px;margin:0 40px 24px 0;color:var(--muted);font-size:11px}.demo-progress-v42:after{content:"";height:4px;flex:1;background:#142c38;border-radius:8px;order:-1}.demo-progress-v42 i{position:absolute;left:26px;top:31px;height:4px;background:var(--cyan);border-radius:8px;max-width:305px;transition:width .25s}.demo-panel-v42 h2{font-size:25px;line-height:1.25;margin:8px 0 12px}.demo-main-v42{color:#c8d5dc;line-height:1.75}.demo-roles-v42{display:grid;gap:8px;margin:20px 0}.demo-roles-v42 article{padding:12px;border:1px solid var(--line2);border-radius:10px;background:rgba(255,255,255,.025)}.demo-roles-v42 b{color:var(--cyan)}.demo-roles-v42 p{margin:4px 0 0;color:var(--muted);line-height:1.55}.demo-actions-v42{display:flex;justify-content:space-between;gap:10px;margin-top:18px}.demo-actions-v42 button{flex:1}.demo-safe-v42{display:block;color:var(--muted);margin-top:14px;line-height:1.5}.demo-target-v42{position:relative;z-index:9998!important;outline:3px solid var(--cyan)!important;outline-offset:5px;box-shadow:0 0 0 9999px rgba(1,7,12,.30),0 0 30px rgba(53,214,232,.35)!important;transition:outline .2s,box-shadow .2s}.demo-running-v42 .top{z-index:auto}@media(max-width:780px){.demo-panel-v42{left:12px;right:12px;top:auto;bottom:12px;width:auto;max-height:58vh;padding:20px}.demo-progress-v42 i{left:20px;top:25px;max-width:240px}.demo-panel-v42 h2{font-size:20px}.demo-roles-v42{grid-template-columns:1fr}.demo-target-v42{scroll-margin-bottom:60vh}}`;document.head.appendChild(s)}
