window.addEventListener('load',()=>{try{installDemoV53()}catch(e){console.error('V5.3 demo failed',e)}},{once:true});
function installDemoV53(){if(!Array.isArray(DEMO_STEPS_V42))return;DEMO_STEPS_V42.splice(0,DEMO_STEPS_V42.length,
 {view:'today',selector:null,kicker:'WELCOME · V5.3',title:'从工作记录到能力补足',text:'Career OS保留原始Daily，再由ChatGPT形成Diagnosis和Learning Response。网站不会覆盖原始记录，也不会管理公司项目状态。',you:'每天自然口述工作、疑问、学习和反馈，最后说“口述结束”。',ai:'整理事实、分析能力信号，并为重要缺口准备材料与训练。',site:'分别保存原始记录、Diagnosis和学习建议。'},
 {view:'today',selector:'[data-quick="daily"]',kicker:'STEP 1 · RECORD',title:'7月15日仍然按原来的方式口述',text:'在当前长期对话里，不需要重新粘贴Prompt。直接继续口述即可。只有换到新对话或其他AI时，才复制网站里的“每日记录与能力补足Prompt”。',you:'描述真实发生的事情，不需要先整理。',ai:'等你说“口述结束”后才开始处理。',site:'新版Prompt已经写明职责边界和输出格式。'},
 {view:'today',selector:'#daily-archive-v53',kicker:'STEP 2 · DAILY ARCHIVE',title:'原始Daily永久保留',text:'7月13日、14日以及以后每天的完整记录都在Daily Archive。它保存工作项、过程、结果、当时不理解的地方和工作中学习。',you:'按日期回看，不需要重复输入。',ai:'不能用后来的分析覆盖当时事实。',site:'对旧版本数据做兼容并提供完整展开。'},
 {view:'today',selector:'#dailyRecordDetailV53',kicker:'STEP 3 · DIAGNOSIS',title:'Diagnosis是分析层，不是事实层',text:'Diagnosis基于当天证据提出可被推翻的判断，例如知识缺口、方法缺口或判断框架不足。单日Diagnosis不会直接升级正式能力。',you:'关注判断依据和限制，不把Diagnosis当成永久标签。',ai:'必须给支持、反对、替代解释和不确定性。',site:'把Diagnosis与对应日期关联展示。'},
 {view:'today',selector:'#problem-learning-v52',kicker:'STEP 4 · LEARNING RESPONSE',title:'把问题转换为学习材料',text:'系统只聚焦工作暴露出的能力缺失：学什么、看什么、怎么练、如何自测。它不追踪责任人、修复进度、回归状态或项目关闭。',you:'选择最相关的主题，按时间决定15分钟、60分钟或2小时版本。',ai:'优先正式Spec、官方资料和公司批准材料，再提供脱敏练习。',site:'保存材料、学习路径、Prompt和自测题。'},
 {view:'today',selector:'.learning-response-card',kicker:'STEP 5 · USE A LEARNING CARD',title:'每张卡片有四种用法',text:'先看核心概念；再选择学习深度；需要继续对话时复制AI Prompt；最后用迁移练习和自测检验是否真正掌握。',you:'不必每天做完所有主题，只选当前最有价值的一项。',ai:'先出题、后评分，不要直接替你完成自测。',site:'让工作问题沉淀为可迁移能力，而不是待办列表。'},
 {view:'growth',selector:'#current-execution',kicker:'STEP 6 · WEEKLY COURSE',title:'Daily问题不会冲散16周课程',text:'Daily只生成学习补足建议。是否进入正式周计划、是否调整课程，由周度Review根据重复性、影响和长期相关度决定。',you:'保持主线课程稳定，临时问题按需补足。',ai:'在周复盘中判断哪些主题值得升级为动态任务。',site:'固定课程与Daily学习建议分层保存。'},
 {view:'growth',selector:'#review-layer-v4',kicker:'STEP 7 · WEEKLY REVIEW',title:'每周再做一次整体判断',text:'导出本周Daily、Diagnosis和Learning Response交给ChatGPT。周复盘才正式确认长期判断和课程轻量调整。',you:'提供本周材料并确认最终结论。',ai:'综合支持证据、反证、独立程度和重复趋势。',site:'保存正式Review，不自行提高Confidence。'},
 {view:'today',selector:'.top-actions',kicker:'FINISH',title:'日常使用只需要两步',text:'第一步：像以前一样口述，最后说“口述结束”。第二步：网站更新后，到Daily Archive查看原始记录，到Learning Response选择一个值得补足的主题。',you:'保持输入自然和真实。',ai:'自动完成记录、分析和学习转化。',site:'成为长期可追溯的记录与成长数据库。'}
 );const b=document.getElementById('openUsageDemo');if(b)b.textContent='使用Demo · V5.3';applyV53Identity()}
