function baseState(){return{version:2,selectedDate:todayISO(),calendarMonth:todayISO().slice(0,7),week:'w1',checks:{},dailyLogs:[],problemLogs:[],weeklyReviews:[],schedule:[],cycleArchives:[{id:'cycle-202607',title:'2026年7月 · Debug与验证工作流',range:'2026-07-13—2026-08-09',status:'进行中',summary:'固定四周周期：工作流、Debug证据链、Spec接入、Corner与验证策略。'}],abilities:DEFAULT_ABILITIES,resume:{filename:'',version:'入职前版本待导入',target:'SoC系统型验证工程师 → 芯片项目负责人',summary:'等待导入入职前简历。',education:[],experiences:[],projects:[],skills:[],awards:[],versions:[],candidates:[]}}}
let S=loadState();
function loadState(){let s;try{s=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}if(s)return Object.assign(baseState(),s);const n=baseState();try{const old=JSON.parse(localStorage.getItem(OLD_KEY)||'null');if(old){n.checks=old.checks||{};n.week=old.week||'w1';if(old.evidence?.length)n.cycleArchives.push({id:'migrated-evidence',title:'旧版成长证据迁移',range:'旧版数据',status:'已迁移',summary:old.evidence.map(x=>`${x.date||''} ${x.title||''}：${x.summary||''}`).join('\n')});if(old.reflection&&Object.values(old.reflection).some(Boolean))n.weeklyReviews.push({id:'migrated-review',week:'旧版周复盘',raw:JSON.stringify(old.reflection,null,2)});}}catch{}return n}
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(x){const t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function list(v){if(!v)return[];return Array.isArray(v)?v:[v]}
function stripJson(s){return s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'')}
function parseInput(text,date){const raw=text.trim();if(!raw)return null;try{const o=JSON.parse(stripJson(raw));if(date&&!o.date)o.date=date;return o}catch{return{date:date||todayISO(),raw}}}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function jump(view){$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(x=>x.classList.toggle('active',x.id===view));window.scrollTo(0,0);renderAll()}
$$('.nav button').forEach(b=>b.onclick=()=>jump(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>jump(b.dataset.jump));
function weekStart(d=new Date()){const x=new Date(d);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(0,0,0,0);return x}
function thisWeekDates(){const s=weekStart(),e=new Date(s);e.setDate(e.getDate()+7);return[s,e]}
function workMetrics(){const [s,e]=thisWeekDates(),logs=S.dailyLogs.filter(x=>{const d=new Date(x.date+'T00:00:00');return d>=s&&d<e});const problems=S.problemLogs.filter(x=>{const d=new Date(x.date+'T00:00:00');return d>=s&&d<e});const learn=logs.reduce((a,x)=>a+list(x.outsideLearning).length,0);return{days:new Set(logs.map(x=>x.date)).size,tasks:logs.reduce((a,x)=>a+list(x.work).length,0),problems:problems.length,learn}}
function learningCalc(){const w=W.find(x=>x.id===S.week),all=W.flatMap(x=>x.items),current=w.items;const pct=a=>a.length?Math.round(a.filter(x=>S.checks[x[0]]).length/a.length*100):0;const tests=all.filter(x=>x[1]==='自测');return{cycle:pct(all),week:pct(current),test:pct(tests),logs:workMetrics().days}}
function renderToday(){const d=S.selectedDate||todayISO();$('#todayDate').value=d;$('#selectedDateTitle').textContent=d;const log=S.dailyLogs.find(x=>x.date===d);const schedules=S.schedule.filter(x=>x.date===d);const items=[];if(log){list(log.work).forEach(x=>items.push({type:'work',title:x.task||'工作任务',text:x.progress||x.status||''}));list(log.outsideLearning).forEach(x=>items.push({type:'learn',title:x.title||'额外学习',text:x.result||''}));list(log.life).forEach(x=>items.push({type:'life',title:x.title||'生活事项',text:x.result||''}))}schedules.forEach(x=>items.push({type:x.type,title:x.title,text:x.time||''}));$('#todayItems').innerHTML=items.length?items.map(x=>`<div class="today-item"><i class="dot ${x.type}"></i><div><b>${esc(x.title)}</b><p>${esc(x.text)}</p></div></div>`).join(''):'<div class="empty">今天还没有记录。口述后，让AI整理并导入。</div>';$('#todayTimeline').innerHTML=schedules.length?schedules.sort((a,b)=>(a.time||'').localeCompare(b.time||'')).map(x=>`<article><time>${esc(x.time||'未设时间')}</time><h4>${esc(x.title)}</h4><p>${x.type==='work'?'工作':x.type==='learn'?'额外学习':'锻炼 / 生活'}</p></article>`).join(''):'<div class="empty">没有单独安排时间线。</div>';const m=workMetrics(),l=learningCalc();$('#todayLogCount').textContent=m.days+' 天';$('#todayLearnPct').textContent=l.week+'%';const w=W.find(x=>x.id===S.week);$('#weekLearningTitle').textContent=w.title;const n=w.items.find(x=>!S.checks[x[0]]);$('#nextAction').textContent=n?n[2]:'本周学习任务已完成';$('#nextActionMeta').textContent=n?n[3]:'进入周度复盘，由AI生成下一步。'}
$('#todayDate').onchange=e=>{S.selectedDate=e.target.value;save();renderAll()};
function renderCalendar(){const [y,m]=S.calendarMonth.split('-').map(Number),first=new Date(y,m-1,1),start=new Date(first);start.setDate(1-((first.getDay()+6)%7));$('#monthTitle').textContent=`${y}年${m}月`;let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=d.toISOString().slice(0,10),other=d.getMonth()!==m-1,marks=[];if(S.dailyLogs.some(x=>x.date===iso))marks.push('work');if(S.problemLogs.some(x=>x.date===iso))marks.push('problem');S.schedule.filter(x=>x.date===iso).forEach(x=>marks.push(x.type));html+=`<div class="day ${other?'other':''} ${iso===todayISO()?'today':''} ${iso===S.selectedDate?'selected':''}" data-date="${iso}"><strong>${d.getDate()}</strong><div class="day-marks">${[...new Set(marks)].map(x=>`<i class="mark ${x}"></i>`).join('')}</div></div>`}$('#calendarGrid').innerHTML=html;$$('.day').forEach(x=>x.onclick=()=>{S.selectedDate=x.dataset.date;save();renderCalendar();renderCalendarDetail()});renderCalendarDetail();$('#scheduleDate').value=S.selectedDate}
function renderCalendarDetail(){const d=S.selectedDate,log=S.dailyLogs.find(x=>x.date===d),probs=S.problemLogs.filter(x=>x.date===d),sc=S.schedule.filter(x=>x.date===d);$('#calendarDayTitle').textContent=d||'选择日期';let arr=[];if(log)arr.push(`<div class="entry"><span class="tag work">工作记录</span><h3>${esc(log.overview||'当日工作记录')}</h3></div>`);probs.forEach(x=>arr.push(`<div class="entry"><span class="tag problem">问题</span><h3>${esc(x.title||'问题日志')}</h3></div>`));sc.forEach(x=>arr.push(`<div class="entry"><span class="tag ${x.type}">${x.type==='work'?'工作':x.type==='learn'?'额外学习':'生活'}</span><h3>${esc(x.title)}</h3><p>${esc(x.time||'')}</p></div>`));$('#calendarDayDetail').innerHTML=arr.length?arr.join(''):'<div class="empty">当天没有记录。</div>'}
$('#prevMonth').onclick=()=>{let d=new Date(S.calendarMonth+'-01T00:00:00');d.setMonth(d.getMonth()-1);S.calendarMonth=d.toISOString().slice(0,7);save();renderCalendar()};$('#nextMonth').onclick=()=>{let d=new Date(S.calendarMonth+'-01T00:00:00');d.setMonth(d.getMonth()+1);S.calendarMonth=d.toISOString().slice(0,7);save();renderCalendar()};
$('#addSchedule').onclick=()=>{const date=$('#scheduleDate').value,title=$('#scheduleTitle').value.trim();if(!date||!title)return toast('请填写日期和标题');S.schedule.push({id:id(),date,type:$('#scheduleType').value,title,time:$('#scheduleTime').value.trim()});save();$('#scheduleTitle').value='';$('#scheduleTime').value='';renderAll();toast('安排已添加')};
function renderWork(){const m=workMetrics();$('#workMetrics').innerHTML=[['本周记录天数',m.days],['工作任务',m.tasks],['问题日志',m.problems],['额外学习记录',m.learn]].map(x=>`<article class="card metric"><small>${x[0]}</small><b>${x[1]}</b><div class="progress"><i style="width:${Math.min(100,x[1]*20)}%"></i></div></article>`).join('');const logs=[...S.dailyLogs].sort((a,b)=>b.date.localeCompare(a.date));$('#dailyFeed').innerHTML=logs.length?logs.map(x=>`<article class="entry"><header><span>${esc(x.date)}</span><button class="danger small-btn" data-del-daily="${x.id}">删除</button></header><h3>${esc(x.overview||'每日工作记录')}</h3>${list(x.work).map(w=>`<div><div class="tag-row"><span class="tag work">工作</span><b>${esc(w.task||'任务')}</b></div><p>${esc(w.progress||w.status||'')}</p>${w.issue?`<p><b>问题与处理：</b>${esc(w.issue)}</p>`:''}${w.next?`<p><b>下一步：</b>${esc(w.next)}</p>`:''}</div>`).join('')}${list(x.workLearning).length?`<p><b>工作中的学习：</b>${list(x.workLearning).map(esc).join('；')}</p>`:''}${list(x.outsideLearning).length?`<div class="tag-row">${list(x.outsideLearning).map(l=>`<span class="tag learn">${esc(l.title||l)}</span>`).join('')}</div>`:''}${list(x.aiObservations).length?`<p><b>AI观察：</b>${list(x.aiObservations).map(esc).join('；')}</p>`:''}</article>`).join(''):'<div class="empty">还没有工作记录。</div>';$$('[data-del-daily]').forEach(b=>b.onclick=()=>{S.dailyLogs=S.dailyLogs.filter(x=>x.id!==b.dataset.delDaily);save();renderAll()})}
$('#dailyDate').value=todayISO();$('#saveDaily').onclick=()=>{const date=$('#dailyDate').value||todayISO(),o=parseInput($('#dailyImport').value,date);if(!o)return toast('请粘贴AI输出');o.id=o.id||id();o.date=o.date||date;S.dailyLogs=S.dailyLogs.filter(x=>x.date!==o.date);S.dailyLogs.push(o);S.selectedDate=o.date;save();$('#dailyImport').value='';renderAll();toast('每日记录已保存')};
function renderProblems(){const a=[...S.problemLogs].sort((x,y)=>y.date.localeCompare(x.date));$('#problemFeed').innerHTML=a.length?a.map(x=>`<article class="entry"><header><span>${esc(x.date)}</span><button class="danger small-btn" data-del-problem="${x.id}">删除</button></header><h3>${esc(x.title||'问题日志')}</h3>${x.raw?`<p>${esc(x.raw)}</p>`:`<p><b>背景：</b>${esc(x.background||'')}</p><p><b>预期 / 实际：</b>${esc(x.expected||'')} / ${esc(x.actual||'')}</p>${list(x.analysis).length?`<ul>${list(x.analysis).map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`:''}<p><b>根因：</b>${esc(x.rootCause||'待确认')}</p><p><b>解决：</b>${esc(x.solution||'')}</p><p><b>理解变化：</b>${esc(x.understanding||'')}</p>`}<div class="tag-row">${list(x.abilities).map(v=>`<span class="tag">${esc(v)}</span>`).join('')}${x.independence?`<span class="tag problem">${esc(x.independence)}</span>`:''}</div></article>`).join(''):'<div class="empty">还没有问题日志。</div>';$$('[data-del-problem]').forEach(b=>b.onclick=()=>{S.problemLogs=S.problemLogs.filter(x=>x.id!==b.dataset.delProblem);save();renderAll()})}
$('#problemDate').value=todayISO();$('#saveProblem').onclick=()=>{const date=$('#problemDate').value||todayISO(),o=parseInput($('#problemImport').value,date);if(!o)return toast('请粘贴AI输出');o.id=o.id||id();o.date=o.date||date;S.problemLogs.push(o);save();$('#problemImport').value='';renderAll();toast('问题日志已保存')};
function renderLearning(){const m=learningCalc();$('#learningMetrics').innerHTML=[['全周期完成',m.cycle+'%'],['本周完成',m.week+'%'],['自测完成',m.test+'%'],['本周工作记录',m.logs+'天']].map(([l,v])=>`<article class="card metric"><small>${l}</small><b>${v}</b><div class="progress"><i style="width:${parseInt(v)||0}%"></i></div></article>`).join('');$('#weekTabs').innerHTML=W.map((w,i)=>`<button data-week="${w.id}" class="${S.week===w.id?'active':''}"><span>W0${i+1}</span><b>${w.dates}</b><small>${w.title}</small></button>`).join('');$$('[data-week]').forEach(b=>b.onclick=()=>{S.week=b.dataset.week;save();renderAll()});const w=W.find(x=>x.id===S.week);$('#weekContent').innerHTML=`<div class="week-head"><div><div class="eyebrow">${w.dates}</div><h2>${w.title}</h2><p>${w.shift}</p></div><div class="tag-row"><span class="tag learn">工作之外学习</span><span class="tag work">工作观察不计完成率</span></div></div><div class="observation"><div class="eyebrow">WORK OBSERVATION</div><h3>工作中的观察点</h3><ul>${w.observations.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="tasks">${w.items.map(i=>`<article class="task ${S.checks[i[0]]?'done':''}"><label><input type="checkbox" data-check="${i[0]}" ${S.checks[i[0]]?'checked':''}><span class="kind ${i[1]==='自测'?'test':''}">${i[1]}</span><div><h3>${i[2]}</h3><small>${i[3]}</small></div></label><div class="task-body"><ol>${i[4].map(x=>`<li>${x}</li>`).join('')}</ol><dl><div><dt>留下什么</dt><dd>${i[5]}</dd></div><div><dt>怎样算会</dt><dd>${i[6]}</dd></div><div><dt>高压降级</dt><dd>${i[7]}</dd></div></dl></div></article>`).join('')}</div>`;$$('[data-check]').forEach(c=>c.onchange=()=>{S.checks[c.dataset.check]=c.checked;save();renderAll()})}
function renderWeekly(){const a=[...S.weeklyReviews].reverse();$('#weeklyFeed').innerHTML=a.length?a.map(x=>`<article class="entry"><header><span>${esc(x.week||'周复盘')}</span><button class="danger small-btn" data-del-weekly="${x.id}">删除</button></header>${x.raw?`<p>${esc(x.raw)}</p>`:`${list(x.workSummary).length?`<h3>工作总结</h3><ul>${list(x.workSummary).map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`:''}${list(x.learningSummary).length?`<h3>额外学习</h3><ul>${list(x.learningSummary).map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`:''}${list(x.repeatedProblems).length?`<p><b>重复问题：</b>${list(x.repeatedProblems).map(esc).join('；')}</p>`:''}${x.nextWeek?`<p><b>下周学习：</b>${list(x.nextWeek.learning).map(v=>esc(v.title||v)).join('；')}</p>`:''}`}</article>`).join(''):'<div class="empty">还没有周复盘。</div>';$$('[data-del-weekly]').forEach(b=>b.onclick=()=>{S.weeklyReviews=S.weeklyReviews.filter(x=>x.id!==b.dataset.delWeekly);save();renderAll()})}
$('#saveWeekly').onclick=()=>{const o=parseInput($('#weeklyImport').value);if(!o)return toast('请粘贴周复盘');o.id=o.id||id();o.week=o.week||$('#weeklyRange').value||'未命名周次';S.weeklyReviews.push(o);if(o.resumeCandidates?.length)S.resume.candidates.push(...o.resumeCandidates.map(x=>({...x,id:id(),source:o.week})));save();$('#weeklyImport').value='';renderAll();toast('周复盘已保存')};
function renderAbilities(){const statusLevel={'尚未展开':1,'初步理解':2,'能够在提示下完成':3,'能够独立完成':4,'能够处理复杂情况':5,'能够形成方法并指导他人':6};$('#abilityGrid').innerHTML=S.abilities.map(a=>`<article class="card ability"><div class="ability-status"><div><div class="eyebrow">ABILITY</div><h3>${esc(a.name)}</h3></div><b>${esc(a.status)}</b></div><div class="level"><i style="width:${(a.level||statusLevel[a.status]||1)/6*100}%"></i></div><p><b>最近信号：</b>${esc(a.signal||'暂无')}</p><p><b>升级条件：</b>${esc(a.next||'待AI补充')}</p></article>`).join('')}
$('#saveAbilities').onclick=()=>{const o=parseInput($('#abilityImport').value);if(!o||!Array.isArray(o.abilities))return toast('能力JSON格式不正确');o.abilities.forEach(u=>{const a=S.abilities.find(x=>x.id===u.id||x.name===u.name);if(a)Object.assign(a,u)});save();$('#abilityImport').value='';renderAll();toast('能力地图已更新')};
function renderResume(){const r=S.resume;$('#resumeTarget').textContent='目标方向：'+(r.target||'待确认');$('#resumeFileInfo').textContent=r.filename?`已记录原始文件：${r.filename}。内容仍以AI导入的结构化档案为准。`:'尚未选择原始简历文件。静态网站只记录文件名；简历内容请先交给AI整理后再导入。';let html=`<div class="eyebrow">CURRENT RESUME · ${esc(r.version||'未命名')}</div><h2>${esc(r.summary||'等待导入入职前简历')}</h2>`;const sec=(title,arr,fn)=>arr?.length?`<div class="resume-section"><h3>${title}</h3>${arr.map(fn).join('')}</div>`:'';html+=sec('教育经历',r.education,(x)=>`<div class="resume-item"><time>${esc(x.time||'')}</time><div><h4>${esc(x.title||'')}</h4><p>${esc(x.detail||'')}</p></div></div>`);html+=sec('工作与实习',r.experiences,(x)=>`<div class="resume-item"><time>${esc(x.time||'')}</time><div><h4>${esc(x.title||'')}</h4><p>${esc(x.detail||'')}</p><div class="tag-row">${list(x.skills).map(v=>`<span class="tag">${esc(v)}</span>`).join('')}</div></div></div>`);html+=sec('项目经历',r.projects,(x)=>`<div class="resume-item"><time>${esc(x.time||'')}</time><div><h4>${esc(x.title||'')}</h4><p>${esc(x.detail||'')}</p></div></div>`);if(r.skills?.length)html+=`<div class="resume-section"><h3>技能</h3><div class="tag-row">${r.skills.map(v=>`<span class="tag">${esc(v)}</span>`).join('')}</div></div>`;$('#resumeDisplay').innerHTML=html;$('#resumeCandidates').innerHTML=r.candidates?.length?r.candidates.map(x=>`<article class="entry"><header><span>${esc(x.source||'候选')}</span><span>${esc(x.status||'证据待补充')}</span></header><h3>${esc(x.title||'简历候选')}</h3><p><b>现有事实：</b>${esc(x.evidence||'')}</p><p><b>仍缺：</b>${esc(x.missing||'')}</p></article>`).join(''):'<div class="empty">还没有简历候选。周复盘和周期总结会逐步生成。</div>'}
$('#resumeFile').onchange=e=>{const f=e.target.files[0];if(!f)return;S.resume.filename=f.name;save();renderResume();toast('已记录简历文件名')};$('#saveResume').onclick=()=>{const o=parseInput($('#resumeImport').value);if(!o||o.raw)return toast('请导入AI整理后的简历JSON');S.resume=Object.assign(S.resume,o);save();$('#resumeImport').value='';renderAll();toast('履历档案已更新')};
function renderArchive(){const a=[...S.cycleArchives].reverse();$('#archiveFeed').innerHTML=a.length?a.map(x=>`<article class="entry"><header><span>${esc(x.range||'周期')}</span><span>${esc(x.status||'已归档')}</span></header><h3>${esc(x.title||'周期档案')}</h3><p>${esc(x.summary||x.raw||'')}</p></article>`).join(''):'<div class="empty">还没有周期档案。</div>'}
$('#saveArchive').onclick=()=>{const o=parseInput($('#archiveImport').value);if(!o)return toast('请粘贴周期总结');o.id=o.id||id();o.title=o.title||'未命名四周周期';o.status=o.status||'已归档';S.cycleArchives.push(o);save();$('#archiveImport').value='';renderAll();toast('周期已归档')};
function renderPrompts(){const names=['daily','problem','weekly','resume'];$('#promptGrid').innerHTML=names.map(k=>`<article class="card prompt-card"><header><div><div class="eyebrow">AI PROMPT</div><h3>${PROMPTS[k].title}</h3></div><button class="primary small-btn copy-prompt" data-prompt="${k}">复制</button></header><p class="muted">${PROMPTS[k].desc}</p><pre>${esc(PROMPTS[k].text)}</pre></article>`).join('');bindCopy()}
function bindCopy(){$$('.copy-prompt').forEach(b=>b.onclick=async()=>{const p=PROMPTS[b.dataset.prompt];try{await navigator.clipboard.writeText(p.text);toast('Prompt已复制')}catch{toast('复制失败，请在Prompt中心手动选择')}})}
$('#exportData').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download=`jett-career-os-${todayISO()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('#importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{S=Object.assign(baseState(),JSON.parse(r.result));save();renderAll();toast('数据已导入')}catch{toast('文件格式错误')}};r.readAsText(f)};$('#clearData').onclick=()=>{if(!confirm('确认清空当前浏览器中的全部记录？'))return;localStorage.removeItem(KEY);S=baseState();save();renderAll();toast('本机数据已清空')};
function renderAll(){renderToday();renderCalendar();renderWork();renderProblems();renderLearning();renderWeekly();renderAbilities();renderResume();renderArchive()}
renderPrompts();bindCopy();renderAll();save();